//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "G:\t\MutatedMobsModFix\Minecraft-Deobfuscator3000\1.12 stable mappings"!

//Decompiled by Procyon!

package mmm.eventHandler;

import net.minecraftforge.common.config.*;

@Config(modid = "mmm", name = "RolikMods/MutatedMobs_Config")
public class ConfigHandler
{
    @Config.Comment({ "The percent chance for a creeper mutant to explode into confetti.(Works only if Creeper Confetti mod is installed!)" })
    public static int O_confettiChance;
    @Config.Comment({ "Set to true if you still want creeper mutant to damage players.(Works only if Creeper Confetti mod is installed!)" })
    public static boolean O_damagesPlayers;
    @Config.Comment({ "Enable Creeper Golems Finishing Move!" })
    public static boolean S_CreeperGolemExplodeOnDeath;
    @Config.Comment({ "Enable Blaze Golems Cooking Food Abillity!" })
    public static boolean S_BlazeGolemCookFoodOnRightClick;
    @Config.Comment({ "Enable Guardian Golems Laser Eye Abillity!(Not working yet!)" })
    public static boolean S_GuardianGolemLaserEye;
    @Config.Comment({ "Evil Creeper Pigs, Creeper Pigs now become agressive to players!" })
    public static boolean S_EvilCreeperPigs;
    @Config.Comment({ "Enable Blaze Skeletons Dual damage when burning!" })
    public static boolean S_BlazeSkeletonDualDamage;
    @Config.Comment({ "Set Mob and Bosses Spawnrate" })
    public static int M_BlazePigSpawnRate;
    public static int M_BlazeSkeletonSpawnRate;
    public static int M_ShulkerGhastSpawnRate;
    public static int M_GhastShulkerSpawnRate;
    public static int M_CreepervokerSpawnRate;
    public static int M_CreeperSpiderSpawnRate;
    public static int M_IlliusionerCreeperSpawnRate;
    public static int M_IlliusionerWitherSkeletonSpawnRate;
    public static int M_EndermanSkeletonSpawnRate;
    public static int M_EnderGolemSpawnRate;
    public static int M_ZombieCreeperSpawnRate;
    public static int M_CreeperPigSpawnRate;
    public static int M_SilverfishCreeperSpawnRate;
    public static int M_SlimeCreeperSpawnRate;
    public static int M_SpiderGuardianSpawnRate;
    public static int M_PigmanSpiderSpawnRate;
    public static int M_WitchSpiderSpawnRate;
    public static int M_SpiderPigSpawnRate;
    public static int M_ZombieSpiderSpawnRate;
    public static int M_SquidGhastSpawnRate;
    public static int M_HuskSpiderSpawnRate;
    public static int M_WitherShulkerSpawnRate;
    public static int M_ShulkerWitherSpawnRate;
    public static int M_GuardianGolemSpawnRate;
    public static int M_SlimeGolemSpawnRate;
    public static int M_CreeperGolemSpawnRate;
    public static int M_BlazeGolemSpawnRate;
    public static int M_ElderSpiderGuardianSpawnRate;
    public static int M_IlliusionerGhastSpawnRate;
    public static int M_SpookSpawnRate;
    public static int M_SquidCreeperSpawnRate;
    public static int M_EndermanCreeperSpawnRate;
    public static int M_EnderSnowmanSpawnRate;
    public static int M_BlazeSnowmanSpawnRate;
    public static int M_SantaSpiderSpawnRate;
    public static int M_WitherGolemSpawnRate;
    public static int M_PolarWolfSpawnRate;
    public static int M_BlendermanSpawnRate;
    @Config.Comment({ "Sets limit for specific type of mobs in one chunk!" })
    public static int Min_MobAmount;
    public static int Max_MobAmount;
    public static int Min_GolemAmount;
    public static int Max_GolemAmount;
    public static int Min_EvilMobAmount;
    public static int Max_EvilMobAmount;
    public static int Min_CreeperMobAmount;
    public static int Max_CreeperMobAmount;
    public static int Min_SpiderMobAmount;
    public static int Max_SpiderMobAmount;
    @Config.Comment({ "Mutated Mobs Health && Attack" })
    public static int HP_BlazeGolem;
    public static int HP_BlazePig;
    public static int HP_BlazeSkeleton;
    public static int HP_BlazeSnowman;
    public static int HP_CreeperGolem;
    public static int HP_CreeperPig;
    public static int HP_CreeperVoker;
    public static int HP_ElderSpiderGuardian;
    public static int HP_EnderGolem;
    public static int HP_EnderCreeper;
    public static int HP_EndermanSkeleton;
    public static int HP_EnderSnowman;
    public static int HP_GhastShulker;
    public static int HP_GuardianGolem;
    public static int HP_HuskSpider;
    public static int HP_IlliusionerCreeper;
    public static int HP_IlliusionerWitherSkeleton;
    public static int HP_IlliusionerGhast;
    public static int HP_ShulkerGhast;
    public static int HP_SilverfishCreeper;
    public static int HP_SpiderCreeper;
    public static int HP_SpiderGuardian;
    public static int HP_SpiderPig;
    public static int HP_SpiderWitch;
    public static int HP_SquidCreeper;
    public static int HP_SquidGhast;
    public static int HP_ZombieCreeper;
    public static int HP_ZombieSpider;
    public static int HP_ZombieSpiderPigman;
    public static int HP_WitherShulker;
    public static int HP_ShulkerWither;
    public static int HP_Spook;
    public static int HP_SantaSpider;
    public static int HP_PolarWolf;
    public static int HP_DeadPolarWolf;
    public static int HP_Blenderman;
    public static int ATK_BlazeGolem_MIN;
    public static int ATK_BlazeGolem_MAX;
    public static int ATK_BlazePig;
    public static int ATK_BlazeSkeleton_Arrow;
    public static int ATK_BlazeSkeleton_Melee;
    public static int ATK_Blenderman_MIN;
    public static int ATK_Blenderman_MAX;
    public static int ATK_CreeperGolem_MIN;
    public static int ATK_CreeperGolem_MAX;
    public static int ATK_DeadPolarWolf;
    public static int ATK_PolarWolf;
    public static int ATK_ElderSpiderGuardian;
    public static int ATK_EnderGolem_MIN;
    public static int ATK_EnderGolem_MAX;
    public static int ATK_EnderSkeleton_Arrow;
    public static int ATK_EnderSkeleton_Melee;
    public static int ATK_GuardianGolem_MIN;
    public static int ATK_GuardianGolem_MAX;
    public static int ATK_HuskSpider;
    public static int ATK_WitherSkeletonIlliusioner;
    public static int ATK_WitherSkeletonIlliusioner_Clone;
    public static int ATK_SlimeGolem_MIN;
    public static int ATK_SlimeGolem_MAX;
    public static int ATK_CreeperSpider;
    public static int ATK_SpiderGuardian;
    public static int ATK_ZombieSpider;
    public static int ATK_ZombieSpiderPigman;
    public static int ATK_SantaSpider;
    public static int ATK_Spook;
    @Config.Comment({ "Set Maximum Slime Monster Size" })
    public static int SIZE_SlimeGolem_MAX;
    public static int SIZE_SlimeCreeper_MAX;
    @Config.Comment({ "Enable/Disable Mobs" })
    public static boolean EnableBlazeGolem;
    public static boolean EnableBlazePig;
    public static boolean EnableBlazeSkeleton;
    public static boolean EnableBlazeSnowman;
    public static boolean EnableCreeperGolem;
    public static boolean EnableCreeperPig;
    public static boolean EnableCreepervoker;
    public static boolean EnableElderSpiderGuardian;
    public static boolean EnableEnderGolem;
    public static boolean EnableEnderSkeleton;
    public static boolean EnableEnderSnowman;
    public static boolean EnableEnderCreeper;
    public static boolean EnableGhastShulker;
    public static boolean EnableGuardianGolem;
    public static boolean EnableHuskSpider;
    public static boolean EnableIlliusionerCreeper;
    public static boolean EnableIlliusionerWitherSkeleton;
    public static boolean EnableIlliusionerGhast;
    public static boolean EnableSlimeGolem;
    public static boolean EnableSlimeCreeper;
    public static boolean EnableShulkerGhast;
    public static boolean EnableSilverfishCreeper;
    public static boolean EnableSpiderCreeper;
    public static boolean EnableSpiderGuardian;
    public static boolean EnableSpiderPig;
    public static boolean EnableSpiderWitch;
    public static boolean EnableSquidCreeper;
    public static boolean EnableSquidGhast;
    public static boolean EnableZombieCreeper;
    public static boolean EnableZombieSpider;
    public static boolean EnableZombieSpiderPigman;
    public static boolean EnableWitherShulker;
    public static boolean EnableShulkerWither;
    public static boolean EnableSpook;
    public static boolean EnableSantaSpider;
    public static boolean EnablePolarWolf;
    public static boolean EnableDeadPolarWolf;
    public static boolean EnableBlenderman;
    @Config.Comment({ "Should defuser work on mutants?" })
    public static boolean CanDefuse;
    @Config.Comment({ "Should Minecraft Check for specific mods?" })
    public static boolean DetectCreeperConfettiMod;
    public static boolean DetectMuchMoreSpidersMod;
    public static boolean DetectMobArmorMod;
    public static boolean DetectExtraCreaturesMod;
    public static boolean DetectUtilityGolemsMod;
    public static boolean DetectExtraAddons;
    
    static {
        ConfigHandler.O_confettiChance = 100;
        ConfigHandler.O_damagesPlayers = false;
        ConfigHandler.S_CreeperGolemExplodeOnDeath = true;
        ConfigHandler.S_BlazeGolemCookFoodOnRightClick = true;
        ConfigHandler.S_GuardianGolemLaserEye = true;
        ConfigHandler.S_EvilCreeperPigs = true;
        ConfigHandler.S_BlazeSkeletonDualDamage = true;
        ConfigHandler.M_BlazePigSpawnRate = 10;
        ConfigHandler.M_BlazeSkeletonSpawnRate = 20;
        ConfigHandler.M_ShulkerGhastSpawnRate = 10;
        ConfigHandler.M_GhastShulkerSpawnRate = 10;
        ConfigHandler.M_CreepervokerSpawnRate = 20;
        ConfigHandler.M_CreeperSpiderSpawnRate = 15;
        ConfigHandler.M_IlliusionerCreeperSpawnRate = 15;
        ConfigHandler.M_IlliusionerWitherSkeletonSpawnRate = 10;
        ConfigHandler.M_EndermanSkeletonSpawnRate = 20;
        ConfigHandler.M_EnderGolemSpawnRate = 0;
        ConfigHandler.M_ZombieCreeperSpawnRate = 20;
        ConfigHandler.M_CreeperPigSpawnRate = 20;
        ConfigHandler.M_SilverfishCreeperSpawnRate = 25;
        ConfigHandler.M_SlimeCreeperSpawnRate = 20;
        ConfigHandler.M_SpiderGuardianSpawnRate = 10;
        ConfigHandler.M_PigmanSpiderSpawnRate = 30;
        ConfigHandler.M_WitchSpiderSpawnRate = 15;
        ConfigHandler.M_SpiderPigSpawnRate = 10;
        ConfigHandler.M_ZombieSpiderSpawnRate = 25;
        ConfigHandler.M_SquidGhastSpawnRate = 10;
        ConfigHandler.M_HuskSpiderSpawnRate = 20;
        ConfigHandler.M_WitherShulkerSpawnRate = 0;
        ConfigHandler.M_ShulkerWitherSpawnRate = 0;
        ConfigHandler.M_GuardianGolemSpawnRate = 0;
        ConfigHandler.M_SlimeGolemSpawnRate = 0;
        ConfigHandler.M_CreeperGolemSpawnRate = 0;
        ConfigHandler.M_BlazeGolemSpawnRate = 0;
        ConfigHandler.M_ElderSpiderGuardianSpawnRate = 0;
        ConfigHandler.M_IlliusionerGhastSpawnRate = 0;
        ConfigHandler.M_SpookSpawnRate = 0;
        ConfigHandler.M_SquidCreeperSpawnRate = 20;
        ConfigHandler.M_EndermanCreeperSpawnRate = 10;
        ConfigHandler.M_EnderSnowmanSpawnRate = 0;
        ConfigHandler.M_BlazeSnowmanSpawnRate = 0;
        ConfigHandler.M_SantaSpiderSpawnRate = 0;
        ConfigHandler.M_WitherGolemSpawnRate = 0;
        ConfigHandler.M_PolarWolfSpawnRate = 10;
        ConfigHandler.M_BlendermanSpawnRate = 0;
        ConfigHandler.Min_MobAmount = 1;
        ConfigHandler.Max_MobAmount = 2;
        ConfigHandler.Min_GolemAmount = 1;
        ConfigHandler.Max_GolemAmount = 1;
        ConfigHandler.Min_EvilMobAmount = 1;
        ConfigHandler.Max_EvilMobAmount = 3;
        ConfigHandler.Min_CreeperMobAmount = 1;
        ConfigHandler.Max_CreeperMobAmount = 3;
        ConfigHandler.Min_SpiderMobAmount = 1;
        ConfigHandler.Max_SpiderMobAmount = 3;
        ConfigHandler.HP_BlazeGolem = 140;
        ConfigHandler.HP_BlazePig = 30;
        ConfigHandler.HP_BlazeSkeleton = 50;
        ConfigHandler.HP_BlazeSnowman = 24;
        ConfigHandler.HP_CreeperGolem = 140;
        ConfigHandler.HP_CreeperPig = 30;
        ConfigHandler.HP_CreeperVoker = 40;
        ConfigHandler.HP_ElderSpiderGuardian = 150;
        ConfigHandler.HP_EnderGolem = 140;
        ConfigHandler.HP_EnderCreeper = 60;
        ConfigHandler.HP_EndermanSkeleton = 60;
        ConfigHandler.HP_EnderSnowman = 46;
        ConfigHandler.HP_GhastShulker = 60;
        ConfigHandler.HP_GuardianGolem = 100;
        ConfigHandler.HP_HuskSpider = 36;
        ConfigHandler.HP_IlliusionerCreeper = 24;
        ConfigHandler.HP_IlliusionerWitherSkeleton = 40;
        ConfigHandler.HP_IlliusionerGhast = 20;
        ConfigHandler.HP_ShulkerGhast = 40;
        ConfigHandler.HP_SilverfishCreeper = 10;
        ConfigHandler.HP_SpiderCreeper = 36;
        ConfigHandler.HP_SpiderGuardian = 50;
        ConfigHandler.HP_SpiderPig = 26;
        ConfigHandler.HP_SpiderWitch = 50;
        ConfigHandler.HP_SquidCreeper = 26;
        ConfigHandler.HP_SquidGhast = 60;
        ConfigHandler.HP_ZombieCreeper = 40;
        ConfigHandler.HP_ZombieSpider = 36;
        ConfigHandler.HP_ZombieSpiderPigman = 36;
        ConfigHandler.HP_WitherShulker = 350;
        ConfigHandler.HP_ShulkerWither = 350;
        ConfigHandler.HP_Spook = 360;
        ConfigHandler.HP_SantaSpider = 250;
        ConfigHandler.HP_PolarWolf = 100;
        ConfigHandler.HP_DeadPolarWolf = 100;
        ConfigHandler.HP_Blenderman = 60;
        ConfigHandler.ATK_BlazeGolem_MIN = 7;
        ConfigHandler.ATK_BlazeGolem_MAX = 20;
        ConfigHandler.ATK_BlazePig = 6;
        ConfigHandler.ATK_BlazeSkeleton_Arrow = 6;
        ConfigHandler.ATK_BlazeSkeleton_Melee = 6;
        ConfigHandler.ATK_Blenderman_MIN = 7;
        ConfigHandler.ATK_Blenderman_MAX = 14;
        ConfigHandler.ATK_CreeperGolem_MIN = 7;
        ConfigHandler.ATK_CreeperGolem_MAX = 21;
        ConfigHandler.ATK_DeadPolarWolf = 10;
        ConfigHandler.ATK_PolarWolf = 10;
        ConfigHandler.ATK_ElderSpiderGuardian = 12;
        ConfigHandler.ATK_EnderGolem_MIN = 6;
        ConfigHandler.ATK_EnderGolem_MAX = 14;
        ConfigHandler.ATK_EnderSkeleton_Arrow = 8;
        ConfigHandler.ATK_EnderSkeleton_Melee = 6;
        ConfigHandler.ATK_GuardianGolem_MIN = 7;
        ConfigHandler.ATK_GuardianGolem_MAX = 15;
        ConfigHandler.ATK_HuskSpider = 5;
        ConfigHandler.ATK_WitherSkeletonIlliusioner = 7;
        ConfigHandler.ATK_WitherSkeletonIlliusioner_Clone = 0;
        ConfigHandler.ATK_SlimeGolem_MIN = 7;
        ConfigHandler.ATK_SlimeGolem_MAX = 15;
        ConfigHandler.ATK_CreeperSpider = 7;
        ConfigHandler.ATK_SpiderGuardian = 8;
        ConfigHandler.ATK_ZombieSpider = 6;
        ConfigHandler.ATK_ZombieSpiderPigman = 7;
        ConfigHandler.ATK_SantaSpider = 10;
        ConfigHandler.ATK_Spook = 10;
        ConfigHandler.SIZE_SlimeGolem_MAX = 3;
        ConfigHandler.SIZE_SlimeCreeper_MAX = 4;
        ConfigHandler.EnableBlazeGolem = true;
        ConfigHandler.EnableBlazePig = true;
        ConfigHandler.EnableBlazeSkeleton = true;
        ConfigHandler.EnableBlazeSnowman = true;
        ConfigHandler.EnableCreeperGolem = true;
        ConfigHandler.EnableCreeperPig = true;
        ConfigHandler.EnableCreepervoker = true;
        ConfigHandler.EnableElderSpiderGuardian = true;
        ConfigHandler.EnableEnderGolem = true;
        ConfigHandler.EnableEnderSkeleton = true;
        ConfigHandler.EnableEnderSnowman = true;
        ConfigHandler.EnableEnderCreeper = true;
        ConfigHandler.EnableGhastShulker = true;
        ConfigHandler.EnableGuardianGolem = true;
        ConfigHandler.EnableHuskSpider = true;
        ConfigHandler.EnableIlliusionerCreeper = true;
        ConfigHandler.EnableIlliusionerWitherSkeleton = true;
        ConfigHandler.EnableIlliusionerGhast = true;
        ConfigHandler.EnableSlimeGolem = true;
        ConfigHandler.EnableSlimeCreeper = true;
        ConfigHandler.EnableShulkerGhast = true;
        ConfigHandler.EnableSilverfishCreeper = true;
        ConfigHandler.EnableSpiderCreeper = true;
        ConfigHandler.EnableSpiderGuardian = true;
        ConfigHandler.EnableSpiderPig = true;
        ConfigHandler.EnableSpiderWitch = true;
        ConfigHandler.EnableSquidCreeper = true;
        ConfigHandler.EnableSquidGhast = true;
        ConfigHandler.EnableZombieCreeper = true;
        ConfigHandler.EnableZombieSpider = true;
        ConfigHandler.EnableZombieSpiderPigman = true;
        ConfigHandler.EnableWitherShulker = true;
        ConfigHandler.EnableShulkerWither = true;
        ConfigHandler.EnableSpook = true;
        ConfigHandler.EnableSantaSpider = true;
        ConfigHandler.EnablePolarWolf = true;
        ConfigHandler.EnableDeadPolarWolf = true;
        ConfigHandler.EnableBlenderman = true;
        ConfigHandler.CanDefuse = true;
        ConfigHandler.DetectCreeperConfettiMod = true;
        ConfigHandler.DetectMuchMoreSpidersMod = true;
        ConfigHandler.DetectMobArmorMod = true;
        ConfigHandler.DetectExtraCreaturesMod = true;
        ConfigHandler.DetectUtilityGolemsMod = true;
        ConfigHandler.DetectExtraAddons = true;
    }
}
