#!/usr/bin/env python3
"""
Script to fix compilation errors in the repo:
- Fix API mismatches (EnumFacing, Vec3d, EnumDifficulty, TranslationKey)
- Fix invalid casts generated by decompiler
- Fix generic type inference issues
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JAVA_SRC = ROOT / 'src' / 'main' / 'java'

def fix_compilation_errors(text: str) -> str:
    # Fix Lists.newArrayList casts
    text = re.sub(r'\(List<([\w\.]+)>[\)]Lists\.newArrayList\(\)', r'Lists.<\1>newArrayList()', text)
    
    # Fix EnumFacing.byIndex -> EnumFacing.getFront
    text = text.replace('EnumFacing.byIndex(', 'EnumFacing.getFront(')
    
    # Fix EnumFacing offsets
    text = text.replace('.getXOffset()', '.getFrontOffsetX()')
    text = text.replace('.getYOffset()', '.getFrontOffsetY()')
    text = text.replace('.getZOffset()', '.getFrontOffsetZ()')
    
    # Fix Vec3d.length() -> Vec3d.lengthVector()
    text = re.sub(r'(vec3d\d*)\.length\(\)', r'\1.lengthVector()', text)
    
    # Fix EnumDifficulty.getId() -> getDifficultyId()
    text = text.replace('.getId()', '.getDifficultyId()')
    
    # Fix Render casts
    text = re.sub(r'super\.doRender\(\(EntityLiving\)entity', 'super.doRender(entity', text)
    text = re.sub(r'super\.doRender\(\(Entity\)entity', 'super.doRender(entity', text)
    text = re.sub(r'super\.shouldRender\(\(EntityLiving\)livingEntity', 'super.shouldRender(livingEntity', text)
    text = re.sub(r'bindEntityTexture\(\(Entity\)entity\)', 'bindEntityTexture(entity)', text)
    text = re.sub(r'getTeamColor\(\(Entity\)entity\)', 'getTeamColor(entity)', text)
    
    # Fix applyRotations cast
    text = re.sub(r'super\.applyRotations\(\(EntityLivingBase\)entityLiving', 'super.applyRotations(entityLiving', text)
    
    # Fix ModelBase casts
    text = re.sub(r'\(ModelBase\)new', 'new', text)
    
    # Fix Optional.of((Object)new
    text = text.replace('Optional.of((Object)new', 'Optional.of(new')
    
    # Fix VISIBLE_MOB_SELECTOR.apply((Object)p_apply_1_)
    text = text.replace('VISIBLE_MOB_SELECTOR.apply((Object)p_apply_1_)', 'VISIBLE_MOB_SELECTOR.apply(p_apply_1_)')
    
    # Fix Sets.newHashSet((Object[])
    text = text.replace('Sets.newHashSet((Object[])', 'Sets.newHashSet(')
    
    # Fix super((EntitySpellcasterIllager)EntityCreepervoker.this)
    text = re.sub(r'super\(\(EntitySpellcasterIllager\)\w+\.this\)', 'super()', text)
    
    # Fix (Class)EntityLivingBase.class
    text = text.replace('(Class)EntityLivingBase.class', 'EntityLivingBase.class')
    
    # Fix boolean cast in dataManager.get
    text = re.sub(r'if \(this\.dataManager\.get\(\(DataParameter\)([\w\.]+)\)\)', r'if ((Boolean)this.dataManager.get((DataParameter)\1))', text)
    
    # Fix targetEntity cast
    text = text.replace('this.targetEntity = (EntityLivingBase)this.player;', 'this.targetEntity = this.player;')
    
    # Fix TranslationKey -> UnlocalizedName
    text = text.replace('.setTranslationKey(', '.setUnlocalizedName(')
    text = text.replace('.getTranslationKey(', '.getUnlocalizedName(')
    
    # Fix ForgeRegistries cast
    text = text.replace('ForgeRegistries.ITEMS.register((IForgeRegistryEntry)Item);', 'ForgeRegistries.ITEMS.register(Item);')
    
    return text

def should_process_file(path: Path) -> bool:
    return path.suffix == '.java'

def process_file(path: Path) -> bool:
    changed = False
    try:
        text = path.read_text(encoding='utf-8')
    except UnicodeDecodeError:
        try:
            text = path.read_text(encoding='latin-1')
        except:
            print(f"Could not read {path}")
            return False
            
    new_text = fix_compilation_errors(text)
    
    if new_text != text:
        path.write_text(new_text, encoding='utf-8')
        changed = True
    return changed

def main():
    src_files = list(JAVA_SRC.rglob('*.java'))
    modified_files = []
    for f in src_files:
        if should_process_file(f):
            try:
                did = process_file(f)
                if did:
                    print('Modified:', f)
                    modified_files.append(f)
            except Exception as e:
                print('Failed to process', f, e)
    print('\nSummary: modified %d files' % len(modified_files))

if __name__ == '__main__':
    main()
